CAMERA_NAMES = [
    'CAM_FRONT',
    'CAM_BACK',
    'CAM_FRONT_LEFT',
    'CAM_FRONT_RIGHT',
]

CAMERA_HORIZONTAL_ZONES = {
    'CAM_FRONT': (0.4, 0.6),
    'CAM_BACK': (0.4, 0.6),
    'CAM_FRONT_LEFT': (0.0, 0.4),
    'CAM_FRONT_RIGHT': (0.6, 1.0),
}

DANGER_CLASSES = {
    'person',
    'bicycle',
    'motorcycle',
    'car',
    'bus',
    'truck',
}

DEFAULT_DATAROOT = 'dataset'
DEFAULT_NUSCENES_VERSION = 'v1.0-mini'
DEFAULT_SAMPLE_START = 90
DEFAULT_SAMPLE_END = 95
DEFAULT_MODEL_PATH = 'models/yolov8n.pt'
DEFAULT_VIDEO_DIR = 'videos'
DEFAULT_VIDEO_CAMERA = 'CAM_FRONT'
VIDEO_PROCESS_EVERY_N_FRAMES = 5
MIN_CONFIDENCE = 0.5
MIN_OBJECT_AREA = 0.001
MIN_ZONE_OVERLAP_RATIO = 0.1
BOTTOM_POSITION_THRESHOLD = 0.65
CONSECUTIVE_WARNING_THRESHOLD = 3
CONSECUTIVE_DANGER_THRESHOLD = 5
